kind = "web"
previewPath = "/"
title = "Sitavan SPS"
version = "1.0.0"
id = "artifacts/sitavan-sps"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25156

[services.development]
run = "pnpm --filter @workspace/sitavan-sps run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/sitavan-sps", "run", "build" ]
serve = "static"
publicDir = "artifacts/sitavan-sps/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25156"
BASE_PATH = "/"
